
export interface Asset {
  id: string;
  name: string;
  strikePrices: number[];
  expiries: string[]; // Dates as strings (e.g., 'YYYY-MM-DD')
  basePremium: number; // Base premium for mock calculations
}

export interface Trade {
  id: string; // Unique ID generated by Firestore
  userId: string; // Firebase Auth User ID
  assetId: string; // e.g., 'NIFTY 50', 'Reliance'
  tradeType: 'Call Option' | 'Put Option';
  strikePrice: number;
  expiry: string; // Date string 'YYYY-MM-DD'
  quantity: number;
  entryPremium: number; // Premium at the time of placing trade
  currentPremium: number; // Current simulated premium
  entryTime: string; // ISO date string
  pnl: number; // Calculated Profit and Loss (currentPremium - entryPremium) * quantity
}

// Represents the structure of user data in Firestore
export interface UserSimulatorData {
    balance: number | null; // User's virtual balance, null if not yet initialized
    trades: Trade[]; // Array of active trades
    totalPnl: number; // Accumulated P&L from closed trades
}
```